version: '3'

services:
  web:
    container_name: web
    image: php:apache
    ports:
      - '1234:80'
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - .env
    volumes:
      - ./public_html:/var/www/html
    restart: always

  db:
    container_name: db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data
    restart: always
